// @routes-hash 398a92ab5a096e1f62ef5d7e7e3c0fc7
import { Express } from "express";

import route1 from "./routes/artStyle/getArtStyle";
import route2 from "./routes/assets/addAssets";
import route3 from "./routes/assets/batchDelete";
import route4 from "./routes/assets/batchGenerationData";
import route5 from "./routes/assets/delAssets";
import route6 from "./routes/assets/getAssetsApi";
import route7 from "./routes/assets/getImage";
import route8 from "./routes/assets/saveAssets";
import route9 from "./routes/assets/updateAssets";
import route10 from "./routes/assetsGenerate/generateAssets";
import route11 from "./routes/assetsGenerate/polishAssetsPrompt";
import route12 from "./routes/delSql/clearDatabase";
import route13 from "./routes/delSql/deleteAllData";
import route14 from "./routes/general/generalStatistics";
import route15 from "./routes/general/getSingleProject";
import route16 from "./routes/general/updateProject";
import route17 from "./routes/login/login";
import route18 from "./routes/modelTest/testAI";
import route19 from "./routes/modelTest/testImage";
import route20 from "./routes/modelTest/testVideo";
import route21 from "./routes/novel/addNovel";
import route22 from "./routes/novel/clearNovel";
import route23 from "./routes/novel/delNovel";
import route24 from "./routes/novel/getNovel";
import route25 from "./routes/novel/updateNovel";
import route26 from "./routes/other/getCaptcha";
import route27 from "./routes/production/getProductionData";
import route28 from "./routes/project/addProject";
import route29 from "./routes/project/delProject";
import route30 from "./routes/project/getProject";
import route31 from "./routes/script/addScript";
import route32 from "./routes/script/delScript";
import route33 from "./routes/script/getScrptApi";
import route34 from "./routes/script/updateScript";
import route35 from "./routes/task/getMyTaskApi";
import route36 from "./routes/task/getTaskCategories";
import route37 from "./routes/task/taskDetails";
import route38 from "./routes/user/getUser";
import route39 from "./routes/user/saveUser";

export default async (app: Express) => {
  app.use("/artStyle/getArtStyle", route1);
  app.use("/assets/addAssets", route2);
  app.use("/assets/batchDelete", route3);
  app.use("/assets/batchGenerationData", route4);
  app.use("/assets/delAssets", route5);
  app.use("/assets/getAssetsApi", route6);
  app.use("/assets/getImage", route7);
  app.use("/assets/saveAssets", route8);
  app.use("/assets/updateAssets", route9);
  app.use("/assetsGenerate/generateAssets", route10);
  app.use("/assetsGenerate/polishAssetsPrompt", route11);
  app.use("/delSql/clearDatabase", route12);
  app.use("/delSql/deleteAllData", route13);
  app.use("/general/generalStatistics", route14);
  app.use("/general/getSingleProject", route15);
  app.use("/general/updateProject", route16);
  app.use("/login/login", route17);
  app.use("/modelTest/testAI", route18);
  app.use("/modelTest/testImage", route19);
  app.use("/modelTest/testVideo", route20);
  app.use("/novel/addNovel", route21);
  app.use("/novel/clearNovel", route22);
  app.use("/novel/delNovel", route23);
  app.use("/novel/getNovel", route24);
  app.use("/novel/updateNovel", route25);
  app.use("/other/getCaptcha", route26);
  app.use("/production/getProductionData", route27);
  app.use("/project/addProject", route28);
  app.use("/project/delProject", route29);
  app.use("/project/getProject", route30);
  app.use("/script/addScript", route31);
  app.use("/script/delScript", route32);
  app.use("/script/getScrptApi", route33);
  app.use("/script/updateScript", route34);
  app.use("/task/getMyTaskApi", route35);
  app.use("/task/getTaskCategories", route36);
  app.use("/task/taskDetails", route37);
  app.use("/user/getUser", route38);
  app.use("/user/saveUser", route39);
}
